### Numpy

In [24]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [25]:
import numpy as np

##### dimensions and shapes

In [26]:
my_array=np.array([ 
     [1,2,3],
     [4,5,6]
])

In [27]:
my_array.shape

(2, 3)

In [28]:
my_array.ndim  # boyut gösterir

2

In [29]:
my_array.size

6

In [30]:
my_array=np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]

])

In [31]:
my_array.ndim

3

In [32]:
my_array.shape

(2, 2, 3)

#### indexing and slicing

In [33]:
my_array=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
my_array[1]

array([4, 5, 6])

In [35]:
my_array[1][0]

4

In [36]:
my_array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array[:2,:2]

array([[1, 2],
       [4, 5]])

In [38]:
my_array[1]=np.array([10,10,10])
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
my_array=np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
my_array.reshape(5,2) # atama yapmıyor

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [53]:
np.eye(3,3)  # köşegeni 1 yapıyor

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
my_array=np.random.random((5,2))
my_array

array([[0.92390896, 0.45822595],
       [0.50913739, 0.49146356],
       [0.91326191, 0.48173932],
       [0.57161834, 0.49895945],
       [0.64057004, 0.21277148]])

In [68]:
my_array=np.random.randint(100, size=[3,2])
my_array

array([[23, 82],
       [16, 29],
       [13, 93]])

In [70]:
np.linspace(5,10,15) # 5-10 arasında 15 sayı getirir

array([ 5.        ,  5.35714286,  5.71428571,  6.07142857,  6.42857143,
        6.78571429,  7.14285714,  7.5       ,  7.85714286,  8.21428571,
        8.57142857,  8.92857143,  9.28571429,  9.64285714, 10.        ])

In [71]:
# any(), all(), full(), 
# concatenate() bir python listesiyle arrayi birleştirip array oluşturuyor

In [73]:
array1=np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
np.concatenate([array1,array1] , axis=1) # eklemeyi değitirebiliyoruz
# axis=1 sütun  bazlı , axis=0 satır bazlı 

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

#### statistic

In [78]:
array1=np.arange(0,10)
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
array1.sum()

45

In [80]:
array1.mean()

4.5

In [81]:
array1.std()

2.8722813232690143

In [82]:
array1.var()

8.25

In [83]:
array1.sum(axis=1)

array([10, 35])

In [84]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [86]:
array2=array1 + 10
array2
array2.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

####  boolean arrays

In [87]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [89]:
a[0],a[-1]

(0, 3)

In [90]:
a[[0,-1]]

array([0, 3])

In [92]:
a[[True,False,False,True]]

array([0, 3])

In [93]:
a>=2

array([False, False,  True,  True])

In [94]:
a.mean()

1.5

In [97]:
a[a>a.mean()] # ortalamadan büyük olanları getir

array([2, 3])

In [101]:
a[~(a>a.mean())] # ortalamadan küçük olanı getirir . harici gibi bişey

array([0, 1])

- 100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun
- 30'dan büyük olanları boolean yöntemi ile filtreleyin

In [103]:
numbers=np.random.randint(0,100,(3,3)) # başka yazım :(100,size=(3,3))
numbers

array([[31, 93,  2],
       [63, 46, 61],
       [86, 56, 68]])

In [105]:
boolean_numbers=numbers>30
boolean_numbers

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [106]:
numbers[boolean_numbers]

array([31, 93, 63, 46, 61, 86, 56, 68])

In [107]:
my_array=np.array([0,1,2,3,4,5,6,7,8,9])
array1=my_array.reshape(5,2)
array2=my_array.reshape(2,5)

In [108]:
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
np.dot(array1,array2) # dot() matrisleri çarpıp bize yeni array veriyor

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [112]:
array2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [113]:
import sys

In [115]:
sys.getsizeof(10)

28

In [116]:
sys.getsizeof(1000**100)

160

In [117]:
np.dtype(int).itemsize

4

In [118]:
sys.getsizeof([1,2,3])

88

In [119]:
np.array([1,2,3]).nbytes

12

In [120]:
# pythonda boyut büyüdükçe daha fazla kaynak tüketimi olucaktır